<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsTestProject>true</IsTestProject>
        <IsPackable>false</IsPackable>
        <RootNamespace>TDesu.Serialization.Tests</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <Compile Include="TestHelpers.fs" />
        <Compile Include="Serialization\PrimitiveTests.fs" />
        <Compile Include="Serialization\TlTests.fs" />
        <Compile Include="Serialization\VectorTests.fs" />
        <Compile Include="Serialization\TlReadBufferTests.fs" />
        <Compile Include="Serialization\TlWriteBufferTests.fs" />
        <Compile Include="Serialization\RoundTripPropertyTests.fs" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\src\TDesu.Telegram.Serialization\TDesu.Telegram.Serialization.fsproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="NUnit" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NUnit3TestAdapter" />
        <PackageReference Include="coverlet.collector" />
        <PackageReference Include="FsCheck" />
    </ItemGroup>
</Project>
